### Find All Content
GET http://localhost:8080/api/content

### Find Content by Id
@id = 1
GET http://localhost:8080/api/content/{{id}}

### Create New Content
POST http://localhost:8080/api/content
Content-Type: application/json

{
  "id": 1,
  "Title": "Example 03",
  "description": "Example 3",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "createdAt": "2025-03-22T08:31:54.772736071",
  "updatedAt": null,
  "url": null
}

### Update Content
PUT http://localhost:8080/api/content/{{id}}
Content-Type: application/json

{
  "id": 1,
  "Title": "Example 04",
  "description": "Example 4",
  "status": "IDEA",
  "contentType": "ARTICLE",
  "createdAt": "2025-03-22T08:31:54.772736071",
  "updatedAt": null,
  "url": null
}

### Delete Content
DELETE http://localhost:8080/api/content/{{id}}